apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: secure-app-alerts
  namespace: monitoring
spec:
  groups:
  - name: secure-app.rules
    rules:
    - alert: BackendPodRestarting
      expr: increase(kube_pod_container_status_restarts_total{namespace="secure-app", container="backend"}[5m]) > 2
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Backend pod restarting frequently"
        description: "Backend container restarted more than 2 times in last 5 minutes."
