apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-binding
  namespace: secure-app
subjects:
- kind: User
  name: operator-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: operator-role
  apiGroup: rbac.authorization.k8s.io
